# Generated by Django 4.1.7 on 2023-03-21 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'author',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pCompany', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('authors', models.ManyToManyField(related_name='books', to='books.author')),
            ],
            options={
                'db_table': 'book',
                'ordering': ['name'],
            },
        ),
    ]
